# root dir
path: D:/IU/s3/Projekt Computer Vision/Traffic Sign Detector/data
# train images (relative to 'path')
train: images/yolo_only/train
# val images (relative to 'path')
val: images/yolo_only/val
# test images (relative to 'path')
#test: images/yolo/test

# Classes
nc: 43
names: [
  "0", "1", "2", "3", "4", "5", "6", "7", "8", "9",
  "10", 11", "12", "13", "14", "15", "16", "17", "18", "19", 
  "20", "21", "22", "23", "24", "25", "26", "27", "28", "29", 
  "30", "31", "32", "33", "34", "35", "36", "37", "38", "39",
  "40", "41", "42"
] 